### ISSUE TITLE
Params cannot be empty on create/edit

### ISSUE THREAD

**Issue by gme88** [moritzmorgenroth/ra-data-prisma#1] opened 2018-08-21 13:14 UTC
Listing works perfect, but can't create/edit any record (using Prisma Cloud), getting this error:

![image](https://user-images.githubusercontent.com/19433889/44403489-dee22a80-a554-11e8-921f-e04a9cc74b04.png)

**Comment by moritzmorgenroth** [comment] 2018-09-02 11:11
Hi @gme88 

Sorry to only get back to you now. You came in at a very early stage :) 

The issue is fixed in the latest release, please try version 0.1.7 and let me know if it worked for you! 

Basic CRUD on not to deeply nested types should work now! 

Thanks for your feedback!

**Closed as completed** 2018-09-02 11:11 UTC
